SELECT DISTINCT S1.USER_ID, S1.PRODUCT_ID
FROM ONLINE_SALE AS S1
WHERE (
    SELECT COUNT(*) 
    FROM ONLINE_SALE AS S2 
    WHERE S1.USER_ID = S2.USER_ID AND S1.PRODUCT_ID = S2.PRODUCT_ID
) >=2
ORDER BY S1.USER_ID ASC, S1.PRODUCT_ID DESC